site_name: Module 3
site_description: Event-Driven Microservices with Camel & Quarkus

nav:
  - Overview: index.md
  - Quarkus: quarkus.md
  - Minio: minio.md
  - Links: links.md

plugins:
  - techdocs-core
